In [1]:
import pandas as pd
import numpy as np

In [6]:
df = pd.DataFrame({'text':['pokemon is a anime',
                           'ash i a pokemon trainer',
                           'a pokemon trainer hunts pokemon',
                           'everytime there is win'],'output':[1,1,0,0]})

df                        

,text,output
0,pokemon is a anime,1
1,ash i a pokemon trainer,1
2,a pokemon trainer hunts pokemon,0
3,everytime there is win,0


In [11]:
%pip install scikit-learn

  Using cached scikit_learn-1.9.0-cp312-cp312-win_amd64.whl.metadata (11 kB)
  Using cached narwhals-2.23.0-py3-none-any.whl.metadata (15 kB)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Using cached scikit_learn-1.9.0-cp312-cp312-win_amd64.whl (8.2 MB)
Using cached narwhals-2.23.0-py3-none-any.whl (458 kB)
   ---------------------------------------- 0.0/36.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/36.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/36.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/36.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/36.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/36.6 MB ? eta -:--:--
    --------------------------------------- 0.5/36.6 MB 645.7 kB/s eta 0:00:56
    --------------------------------------- 0.5/36.6 MB 645.7 kB/s eta 0:00:56
    --------------------------------------- 0.5/36.6 MB 645.7 kB/s eta 0:00:56
    ------


[notice] A new release of pip is available: 25.0.1 -> 26.1.2
[notice] To update, run: C:\Users\amanp\OneDrive\Desktop\Gen AI\module1\.venv\Scripts\python.exe -m pip install --upgrade pip


In [12]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [14]:
# bow
bow = cv.fit_transform(df['text'])

In [15]:
# vocabulary
print(cv.vocabulary_)

{'pokemon': 5, 'is': 4, 'anime': 0, 'ash': 1, 'trainer': 7, 'hunts': 3, 'everytime': 2, 'there': 6, 'win': 8}


In [16]:
bow.toarray()

array([[1, 0, 0, 0, 1, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 1, 0, 1, 0],
       [0, 0, 0, 1, 0, 2, 0, 1, 0],
       [0, 0, 1, 0, 1, 0, 1, 0, 1]])

In [17]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())
print(bow[3].toarray())

[[1 0 0 0 1 1 0 0 0]]
[[0 1 0 0 0 1 0 1 0]]
[[0 0 0 1 0 2 0 1 0]]
[[0 0 1 0 1 0 1 0 1]]


In [18]:
# new data
cv.transform(['Garry Watch Ash']).toarray()

array([[0, 1, 0, 0, 0, 0, 0, 0, 0]])

In [19]:
X = bow.toarray()
y = df['output']

In [20]:
# TF - IDF (term freq - inverse document frequency)

df = pd.DataFrame({'text':['pokemon is a anime',
                           'ash i a pokemon trainer',
                           'a pokemon trainer hunts pokemon',
                           'everytime there is win'],'output':[1,1,0,0]})

df                        

,text,output
0,pokemon is a anime,1
1,ash i a pokemon trainer,1
2,a pokemon trainer hunts pokemon,0
3,everytime there is win,0


In [23]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfid = TfidfVectorizer()

In [25]:
arr = tfid.fit_transform(df['text']).toarray()

In [26]:
arr

array([[0.70203482, 0.        , 0.        , 0.        , 0.55349232,
        0.44809973, 0.        , 0.        , 0.        ],
       [0.        , 0.70203482, 0.        , 0.        , 0.        ,
        0.44809973, 0.        , 0.55349232, 0.        ],
       [0.        , 0.        , 0.        , 0.55459491, 0.        ,
        0.7079815 , 0.        , 0.437249  , 0.        ],
       [0.        , 0.        , 0.52547275, 0.        , 0.41428875,
        0.        , 0.52547275, 0.        , 0.52547275]])

In [28]:
print(tfid.idf_)

[1.91629073 1.91629073 1.91629073 1.91629073 1.51082562 1.22314355
 1.91629073 1.51082562 1.91629073]
